---
apiVersion: v1
kind: Service
metadata:
  name: shared-services-registry
  namespace: cross-cluster-connectivity
spec:
  ports:
  - port: 443
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: shared-services-registry
  namespace: cross-cluster-connectivity
subsets:
  - addresses:
    - ip: SHARED_SERVICE_NODE_IP # update to use an actual node IP of the shared service cluster
    ports:
    - port: 30001
---
apiVersion: connectivity.tanzu.vmware.com/v1alpha1
kind: RemoteRegistry
metadata:
  name: shared-services-registry
  namespace: cross-cluster-connectivity
spec:
  address: "shared-services-registry.cross-cluster-connectivity.svc:443"
  tlsConfig:
    serverCA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU0akNDQXNxZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFSTVE4d0RRWURWUVFERXdabVlXdGwKUTBFd0hoY05NakF4TURJd01Ua3lORFV6V2hjTk1qSXdOREl3TVRreU5EUTRXakFSTVE4d0RRWURWUVFERXdabQpZV3RsUTBFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUR4bmxsWmdDdkdZNEVCCkF2WWozdHg2SnFkbmdUanhhdUNWN3ZWUlhqWmpGQm5IOWtVOEE0NzFOblQ2ckdTNVZZU2l6Q0pHL0pDdVRBemMKZDBCc1FlQ2loNXEycWlXRi9XcXVzRm5DZ2hESFZTN2hnOTFJVWlqRWJoTXpsTFhiSnovRmVvOXdydlh5RXE3bQpxZE5hVmROQXVYQzU3cHJubGlhSVM0SkJ3N0F3SExva1JaU21kM3NsWWFQWE9VUlFsTGZ3V3JFMWNqWHB5RGRKCkF4QmhaaURoVnRkbDFISVdNTTJPdW5Hb0RhVCtzdTlHVXQvZ2FUWDR1U2pRbE1Zbk9vWWlWc1NXSGwweVRUMUUKcytwUEhjU21JM3JMdXUzYzVRd3oxMlMxdE1tMGFKZllZRUhXMnFvVnpha0RGSHY0R01KZUNJS3p1RzdNdlI3TwoxYWJXbVpJVG44M1lCRVh5VDQ2TUsrOTdEUkR5SFNUMTJPRFdSdUdJbFhzaVdMUzUzL0pYcDdZOEt3Y2RZbUhVClB5TTZ4SUJXQ3pMeVlDMEp0ZGlGN0loOENucUFOY3pVcUwyTEE3azBreVVydThobk9iTnlRcU9IbytvM2N3dk0KWFNURG04ZStHWERhdTIwbGJzS003WVhTWW52clgzZ2RpQ0EraUlNejFTclgvYkVuNUpqMnB4dXRpaThaaXVWVQo3V3JnWHVtTzJsYVZCc09NUkxqUTNXMVlTK1dvUUhTcmkzWEZxQno2a1ppVUVsZWVVSjM2aFg2bUVtSEtXbXpFCnhIZUgvY1QrMjhZemtUcHZaS2VWQ045QVZXQVdqd1pvZzM0bnhIcE5iZkhSMkk1WDlSZ2RQVTIxRlZxOHlUNDkKbGtBY3pXMWtTeVFSYXFnQWVMYVJpUU9EQlVIK1J3SURBUUFCbzBVd1F6QU9CZ05WSFE4QkFmOEVCQU1DQVFZdwpFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREFkQmdOVkhRNEVGZ1FVTFZVamE1dVNzRUcrTDRYcVdQU05XbVJQCjl0OHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQUhvOTNoclFmSTdPVmVSaFh6aGUweXFzbXpTWG5wZWI5SnoKQlZSalFJVFVsMVYwRjBJRmxHcVJ4RDU5UDR5SEszMkFnTEsyWGdNa2NHU0lDOEx5VkZWa1pnVFRieXdKeWRTcAoveVJpTGRqUlpReEZOZkpaY3RlczRjc3AxNFVsVWJCVjBJNk1JY0ZhRExHY0xCdFU2VzYvdDVnRExPSVZrUEdyCnB5VzhPN3poeFppMkRSUGhWdXU0VE93UGtqYjVPQWJ5Y3QrdmI1SkJaS3ZtcG9ZZE5ocXdac0hiUmJmV1l3Q3QKOXdLSU05NlBlbHF5aVJDNWcrVkU0SFhNaXByaGVGbFNuQW5aZHBRekZxVU40NmFaWTIvNUhPUkl3ZUNROHFJdwpMM2FvS2pRNHdiWFRoRXBTcWZnOWM2c1liZHg0QXlpb0pIOUxQVmxPMDRXZGt2ZUxRdkovU243bmR5eFBmTWZvCkVHVFdOemo3MWxNVEQ3aENuSm0rR1p3UGxWM2t3Qi9qRWM0WXZmdGkwY1RFajJENVlvckVBVDhsNjlBdjZmL00KZVI4Q2M3bytsbXhRem41bTZRdVFzNkJMejlMaUFXNVVSTGRSczBYc1d2QWVia0JrMjRjUnlnVFQxeUtYMTBSMApMQUhvNHdGaElxN3BDSDZPckx0ZFdKT3o2Mmt6clNSRFlaaWpNYlB4WDBuS0lNc05wcENoenJLdHREWm45dlphCmZRZ04zbjJFOWc4S3FHdDFuM01mZGJaWDNhUmVUR213MjBFRXdWQUlGSEZ4RUxBYjhzQ0cxanpzZUtrT2JVQlcKb0FKRlg2dHdYaEhwL3U4L3NZR2loUWVqeUY0ZmE5MnhrTm85YnMvZlJNMVRqdm1LdXF3MGVSMnkybDY3UVJHcgpFOFNwMnB2MQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    serverName: "shared-services-registry.xcc.test"
